### ISSUE TITLE
Sourcemap point to missing source files

### ISSUE THREAD

**Issue by mrcego** [baiwusanyu-c/unplugin-vue-ce#12]
Hi @baiwusanyu-c!

I'm not sure what's going on here, and I don't know if this issue is related to dependency, but when I work with CE, Terminal shows warnings: 

![Captura de pantalla 2023-06-15 a la(s) 8 49 57 a m](https://github.com/baiwusanyu-c/unplugin-vue-ce/assets/65884507/af25faa6-4f1b-49ad-894b-974fd8ab697c)

I was testing [here](https://stackblitz.com/edit/vitejs-vite-jesxqs?file=ce%2Ftailwind.config.js) too and I was able to reproduce. 
Type `pnpm dev:ce` for see the warnings. Thanks in advance.

**Comment by baiwusanyu-c** [comment]
These warnings are because I did not generate "SourceMap". Usually, the compilation plug-in (such as "Vue-MARCOS") used in our project will compile our project code. Generate "SourceMap" to facilitate developers debug. And "Unplugin-Vue-CE" is described as "Readme.md", it is injected with the "Vue" source code. This is a behavior that modifys the dependence code, so it does not need to generate "SourceMap". If everything is normal, you can ignore these warnings

**Comment by mrcego** [comment]
Perfect, I will close this issue safely then. Thanks again for the support @baiwusanyu-c ;)
